;窗口
extern curWindow:dword
;窗体
extern gameX:dword
extern gameY:dword
;时间
extern restTime:dword

;得分
extern goalScore:dword
extern playerScore:dword
;矿工
extern minerPosX:dword
extern minerPosY:dword
;钩索
extern hookStat:dword
extern hookDir:dword
extern hookOmega:dword
extern hookV:dword
extern hookDeg:dword
extern hookPosX:dword
extern hookPosY:dword
;物体
extern lastHit:dword
extern itemNum:dword
;商店
extern tool1:dword
extern tool2:dword
extern tool3:dword
extern tool4:dword



extern price1:dword
extern price2:dword
extern price3:dword
extern price4:dword
;extern price5:dword
;extern price6:dword

extern fireNum:dword

extern count:dword



